apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  maxReplicas: 30
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: backend


